### ISSUE TITLE
Links with additional %60 added, breaking redirects

### ISSUE THREAD

**Issue by elwayman02** [emberobserver/client#23]
I've encountered several addons today that have %60 added to the end of the repo url, causing the redirect to github to break when clicked.

Example: http://emberobserver.com/addons/ember-cli-number-abbr

**Comment by pgengler** [comment]
This should be fixed now.

The problem was that the data from NPM for this addon included a backtick (which, when URL-encoded, is %60). Most likely this happened because the `package.json` file for the addon doesn't specify its repository URL, so NPM tries to get it from other sources, including the README.md file. In this case, the repo URL does appear, but it's part of a Markdown inline-code block (enclosed by backticks) and the closing backtick is parsed by NPM as part of the URL.
