### ISSUE TITLE
How are packages added to emberobserver?

### ISSUE THREAD

**Issue by philipbjorge** [emberobserver/client#26]
I just created/published a package and was wondering how they get added to ember observer?

https://github.com/philipbjorge/ember-cli-typescript-compiler

**Comment by kategengler** [comment]
Addons get picked up hourly from npm. The reviews and categorization are still done manually, we usually get to it within a few days but lately its taking ~ a week.

**Comment by sivakumar-kailasam** [comment]
@kategengler is the process still manual? If so, it might probably help to add info on the review timeframe in the _what's this_ section when scores are at NA. My [addon](https://emberobserver.com/addons/ember-purify) has been published 8 days ago and I've been since waiting and it would've helped to see this info on the ember observer site.
